export const EVENTFLOW_SUPPLIER_CATEGORIES = Object.freeze([
  'Venues',
  'Catering',
  'Photography',
  'Videography',
  'Entertainment',
  'Music/DJ',
  'Florist',
  'Decor',
  'Transport',
  'Cake',
  'Stationery',
  'Hair & Makeup',
  'Beauty',
  'Bridalwear',
  'Jewellery',
  'Celebrant',
  'Event Planner',
  'Wedding Fayre',
  'Planning',
  'Other',
] as const);

export const PHASE_ONE_LOCATIONS = Object.freeze([
  'South Wales',
  'North Wales',
  'Mid Wales',
  'Cardiff',
  'Swansea',
  'Newport',
  'Bridgend',
  'Rhondda Cynon Taf',
  'Vale of Glamorgan',
  'Caerphilly',
  'Monmouthshire',
  'Neath Port Talbot',
] as const);
