import { getDatabase } from '../lib/mongo.js';

// Collections holding data acquired/generated by a run of the pipeline --
// wiped by a hard reset so the operator can start again from a clean slate.
// Deliberately excludes:
//  - bot_settings, campaigns: operator configuration, not acquired data
//  - runtime_counters, ai_usage, provider_usage, provider_circuits: real
//    daily budget/spend ledgers and health state, not "junk" to clear
//  - worker_heartbeats: live infra state
//  - audit_events: the audit trail is meant to survive a reset -- the reset
//    itself is recorded into it, not wiped by it
//  - suppression: deliberate do-not-crawl/do-not-list/do-not-contact
//    decisions must never be cleared by a data reset
//  - eventflow_pilot_state: the Hensol one-profile pilot's own state is
//    intentionally left untouched by the general Shadow pipeline reset
//  - published_suppliers: the durable "this domain is already a live
//    EventFlow supplier" record (published-supplier.repository.ts). It must
//    survive a reset -- that's the entire point of it. Wiping candidates
//    without it would make every already-published supplier look brand new
//    to the next discovery cycle, which re-crawls, re-extracts and
//    re-assesses (real crawl/AI spend) a supplier that's already live.
const RESET_COLLECTIONS = [
  'candidates',
  'shadow_profiles',
  'compliance_assessments',
  'dedup_assessments',
  'supplier_identities',
  'supplier_identity_keys',
  'evidence_fragments',
  'ai_extractions',
  'eventflow_ingestions',
  'validation_runs',
] as const;

export async function performHardReset(): Promise<Record<string, number>> {
  const db = await getDatabase();
  const deletedCounts: Record<string, number> = {};
  for (const name of RESET_COLLECTIONS) {
    const result = await db.collection(name).deleteMany({});
    deletedCounts[name] = result.deletedCount;
  }
  return deletedCounts;
}
